vim.keymap.set("n", "<leader>w", function()
  vim.cmd("write")
  vim.cmd("edit")
end, { desc = "Save + Reload" })
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit" })
vim.keymap.set("n", "<leader>e", "<cmd>NvimTreeToggle<CR>", { desc = "File Tree" })
